# netlify.toml

[build]
  # Directorio de salida de la aplicación después del build
  publish = "dist/models-and-controls"  # Asegúrate de que este sea el directorio correcto donde están tus archivos estáticos

[[headers]]
  # Aplicar encabezados CORS al archivo remoteEntry.js
  for = "/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, Content-Type, Accept"

[[redirects]]
  # Redirigir todas las rutas de la app al index.html (Single Page Application)
  from = "/*"
  to = "/index.html"
  status = 200



