[build]
  # Directorio de salida de la aplicación después del build
  publish = "dist/models-and-controls"  # Asegúrate de que este sea el directorio correcto donde están tus archivos estáticos


[[redirects]]
  # Redirigir todas las rutas de la app al index.html (Single Page Application)
  from = "/*"
  to = "/index.html"
  status = 200



